---
title: "final_project"
author: "Antonietta"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggdist)
```

```{r data, setup, include=FALSE}

if (!dir.exists(here::here("FP", "data"))) {
  dir.create(here::here("FP", "data"), recursive = TRUE)
}
covid_data <- read_csv(here::here("FP", "data", "prison_covid.csv"),
                       na = c("", "NaN", "Inf", "-Inf", "NA"))
pop_data <- read_csv(here::here("FP", "data", "prison_populations.csv"),
                     na = c("", "NaN", "Inf", "-Inf", "NA"))
staff_data <- read_csv(here::here("FP", "data", "staff_populations.csv"),
                       na = c("", "NaN", "Inf", "-Inf", "NA"))
```

For this project, I will only be looking at prisons COVID-19 rates for the state of New York; I will  be looking at the total prisoners cases, and deaths compared to recovery. I will also be looking at the total number of staffs' cases, which could have let to high number of prisoner's cases. 

```{r}
ny_cases <- covid_data %>%
  filter(name == "New York") %>%
  select(total_prisoner_cases, total_prisoner_deaths, prisoners_recovered, total_staff_cases, as_of_date)
```

```{r}
ny_cases %>%
  group_by(total_prisoner_cases, total_prisoner_deaths) %>%
  summarise(across(c(total_staff_cases),
    list(
      mean = ~ mean(.x, na.rm = TRUE),
      sd = ~ sd(.x, na.rm = TRUE),
      min = ~ min(.x, na.rm = TRUE),
      max = ~ max(.x, na.rm = TRUE))))
```
    

```{r}
ny_cases %>%
  ggplot(aes(x = as_of_date,
      y = total_prisoner_cases)) + 
  geom_point(alpha= 5, 
             shape= 20,
             color="#C8A2C8",
        fill= "#C8A2C8") +
  scale_y_continuous("Prisoners COVID-19 Cases") +
  scale_x_discrete("Date") +
  ggtitle("New York Prisoners' COVID-19 Cases") +
  theme_light()

 #theme(axis.text = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
```

```{r}
ny_cases %>%
  ggplot(aes(x = total_staff_cases,
      y = total_prisoner_cases)) + 
  geom_point(alpha= 5, 
             shape= 20,
             color="#C8A2C8",
        fill= "#C8A2C8") +
  geom_smooth(method = "loess") +
  scale_y_continuous("Prisoners COVID-19 Cases") +
  scale_x_discrete("Prison Staff COVID-19 Cases") +
  ggtitle("New York Prisoners' COVID-19 Cases") +
  theme_light()
```
```{r}
ny_cases %>%
  ggplot(aes(x = total_prisoner_cases,
      y = prisoners_recovered)) + 
  geom_point(alpha= 5, 
             shape= 20,
             color="#C8A2C8",
        fill= "#C8A2C8") +
  geom_smooth(method = "loess") +
  scale_y_continuous("Prisoners COVID-19 Cases") +
  scale_x_discrete("Prisoners Recovered") +
  ggtitle("New York Prisoners' COVID-19 Cases") +
  theme_light()
```
```{r}
ny_cases %>%
  ggplot(aes(x = total_prisoner_cases,
      y = total_prisoner_deaths)) + 
  geom_point(alpha= 5, 
             shape= 20,
             color="#C8A2C8",
        fill= "#C8A2C8") +
  geom_smooth(method = "loess") +
  scale_y_continuous("Prisoners COVID-19 Cases") +
  scale_x_discrete("Prisoners Death by COVID-19") +
  ggtitle("New York Prisoners' COVID-19 Cases") +
  theme_light()
```