---
title: "hw04"
author: "Antonietta"
date: "3/8/2021"
output:   
  github_document: default
  html_document: default


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```


```{r data, setup, include=FALSE}

if( !dir.exists(here::here("FINAL_PROJECT","data"))) {
  dir.create(here::here("FINAL_PROJECT","data"), recursive =TRUE)
}

adhd_data <- read_csv(here::here("FINAL_PROJECT","data","adhd.csv"),
  na = c("", "NaN", "Inf", "-Inf", "NA"))

```

# Summary

```{r, practicing summary}

adhd_data %>%
  group_by(Ethnicity, Measure, Score) %>%
  summarise(across(c(Value),
            list(
              mean = ~mean(.x, na.rm = TRUE),
              sd = ~sd(.x, na.rm = TRUE), 
              min = ~min(.x, na.rm = TRUE),
              max = ~max(.x, na.rm = TRUE)
              
            )))

```


# Plots 


```{r, practicing plots}

plot_adhd <- adhd_data %>%
  ggplot()+
  aes(x = Ethnicity,
      y = Value) +
  geom_point(fill = "purple" , 
             color = "purple", 
             alpha = .5,
             size = 2,
             shape = 20) +
  theme_minimal()

plot_adhd



```


# Output

```{r, output }

write_csv(adhd_data , here::here("FINAL_PROJECT", "data", "adhd_data" ))

ggsave(here::here("FINAL_PROJECT", "output","figures", "plot_adhd.pdf"))
       
```


